package com.baolong.pictures.infrastructure.api.bailian.model;

import cn.hutool.core.annotation.Alias;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

import java.io.Serializable;

/**
 * 扩图任务请求
 *
 * @author Silas Yan 2025-03-24:22:29
 */
@Data
public class ExpandImageTaskRequest {

	/**
	 * 模型，例如 "image-out-painting"
	 */
	private String model = "image-out-painting";

	/**
	 * 输入图像的基本信息，比如图像URL地址
	 */
	private Input input;

	/**
	 * 图像处理参数
	 */
	private Parameters parameters;

	@Data
	@NoArgsConstructor
	@AllArgsConstructor
	public static class Input {
		/**
		 * 必填: 图像 URL 或者 base64
		 * <p>
		 * 图像格式: JPG、JPEG、PNG、HEIF、WEBP。
		 * <p>
		 * 图像大小: 不超过10MB。
		 * <p>
		 * 图像分辨率: 不低于512×512像素且不超过4096×4096像素。
		 * <p>
		 * 图像单边长度范围: [512, 4096]，单位像素。
		 */
		@Alias("image_url")
		private String imageUrl;
	}

	@Data
	@Accessors(chain = true)
	public static class Parameters implements Serializable {
		/**
		 * 逆时针旋转角度。默认值为0，取值范围[0, 359]。
		 * <p>
		 * angel参数需要与x_scale、y_scale参数或者top_offset、bottom_offset、left_offset 、right_offset参数搭配使用，保证旋转角度有足够的空间扩图。
		 */
		private Integer angle;

		/**
		 * 图像宽高比。可选值有["","1:1", "3:4", "4:3", "9:16", "16:9"]。默认为""，表示不设置输出图像的宽高比。
		 * <p>
		 * 相较于比例参数或者添加像素数参数，output_ratio参数的优先级最高。如果output_ratio取值不为空字符串，将使用该参数输出图像。
		 * <p>
		 * 扩展参数优先级
		 * <p>
		 * 1、若output_ratio不为空，使用高宽比参数输出图像。
		 * <p>
		 * 2、若扩展比例（x_scale，y_scale）不全为1，使用扩展比例。
		 * <p>
		 * 3、其他情况使用扩展像素值（parameters.left_offset，parameters.right_offset，parameters.top_offset，parameters.bottom_offset）
		 */
		@Alias("output_ratio")
		private String outputRatio;

		/**
		 * 图像居中，在水平方向上按比例扩展图像。
		 * <p>
		 * 默认值为1.0，取值范围[1.0, 3.0]。
		 * <p>
		 * 您可以选择与y_scale参数搭配使用，但不能与top_offset、bottom_offset、left_offset
		 * 、right_offset这些参数同时使用。若同时配置，则x_scale、y_scale参数优先生效。
		 * <p>
		 * 例如：输入图像分辨率为1000×1000（宽×高），x_scale=2.0，扩展后的图像分辨率为2000×1000（宽×高）。保持高度不变，左右各添加500个像素。
		 */
		@Alias("x_scale")
		@JsonProperty("xScale")
		private Float xScale;

		/**
		 * 图像居中，在垂直方向上按比例扩展图像。
		 * <p>
		 * 默认值为1.0，取值范围[1.0, 3.0]。
		 * <p>
		 * 您可以选择与x_scale参数搭配使用，但不能与top_offset、bottom_offset、left_offset、right_offset这些参数同时使用。若同时配置，则x_scale、y_scale参数优先生效。
		 * <p>
		 * 例如：输入图像分辨率为1000×1000（宽×高），y_scale=2.0，扩展后的图像分辨率为1000×2000（宽×高）。保持宽度不变，上下各添加500个像素。
		 */
		@Alias("y_scale")
		@JsonProperty("yScale")
		private Float yScale;

		/**
		 * 在图像上方添加像素。
		 * <p>
		 * 默认值为0，取值限制top_offset+bottom_offset < 3×输入图像高度。
		 * <p>
		 * 例如：输入图像分辨率为1000×1000（宽×高），top_offset=500，扩展后的图像分辨率为1000×1500（宽×高）。保持宽度不变，只在图像上方添加500个像素。
		 * <p>
		 * 您可以选择与bottom_offset、left_offset
		 * 、right_offset参数搭配使用，但不能与x_scale、y_scale这些参数同时使用。若同时配置，则x_scale、y_scale参数优先生效。
		 */
		@Alias("top_offset")
		private Integer topOffset;

		/**
		 * 在图像下方添加像素。
		 * <p>
		 * 默认值为0，取值限制top_offset+bottom_offset < 3×输入图像高度。
		 * <p>
		 * 例如：输入图像分辨率为1000×1000（宽×高），bottom_offset=500，扩展后的图像分辨率为1000×1500（宽×高）。保持宽度不变，只在图像下方添加500个像素。
		 * <p>
		 * 您可以选择与top_offset、left_offset 、right_offset参数搭配使用，但不能与x_scale、y_scale这些参数同时使用。若同时配置，则x_scale、y_scale参数优先生效。
		 */
		@Alias("bottom_offset")
		private Integer bottomOffset;

		/**
		 * 在图像左侧添加像素。
		 * <p>
		 * 默认值为0，扩展限制left_offset+right_offset < 3×输入图像宽度。
		 * <p>
		 * 您可以选择与top_offset、bottom_offset、right_offset参数搭配使用，但不能与x_scale、y_scale这些参数同时使用。若同时配置，则x_scale、y_scale参数优先生效。
		 * <p>
		 * 例如：输入图像分辨率为1000×1000（宽×高），left_offset=500，扩展后的图像分辨率为1500×1000（宽×高）。保持高度不变，只在图像左侧添加500个像素。
		 */
		@Alias("left_offset")
		private Integer leftOffset;

		/**
		 * 在图像右侧添加像素。
		 * <p>
		 * 默认值为0，扩展限制left_offset+right_offset < 3×输入图像宽度。
		 * <p>
		 * 您可以选择与top_offset、bottom_offset、left_offset参数搭配使用，但不能与x_scale、y_scale这些参数同时使用。若同时配置，则x_scale、y_scale参数优先生效。
		 * <p>
		 * 例如：输入图像分辨率为1000×1000（宽×高），right_offset=500，扩展后的图像分辨率为1500×1000（宽×高）。保持高度不变，只在图像右侧添加500个像素。
		 */
		@Alias("right_offset")
		private Integer rightOffset;

		/**
		 * 开启图像最佳质量模式。默认值为false，减少图像生成的等待时间。
		 * <p>
		 * 如果您需要更多图像细节，可以设置为true，但耗时会成倍增加。
		 */
		@Alias("best_quality")
		private Boolean bestQuality;

		/**
		 * 限制模型生成的图像文件大小。默认值为true，限制为：
		 * <p>
		 * 当输入图像单边长度<=10000时，输出图像文件大小在5MB以下。
		 * <p>
		 * 当输入图像单边长度>10000时，输出图像文件大小在10MB以下。
		 * <p>
		 * 输出图像的长宽比范围为1:4至4:1。
		 * <p>
		 * 建议设置为true，模型生成的图像需要经过一层绿网安全过滤后才能输出。当前绿网不支持大于10M的图像处理。
		 */
		@Alias("limit_image_size")
		private Boolean limitImageSize;

		/**
		 * 添加Generated by AI水印。默认值为True，在输出图像左下角处添加水印。
		 */
		@Alias("add_watermark")
		private Boolean addWatermark = false;
	}
}
